<a href="https://colab.research.google.com/github/yziyay/OpenCV-Python-Series/blob/master/berturk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np # linear algebra   +
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [19]:
! git clone https://github.com/NVIDIA/apex
! cd apex
! pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" /kaggle/working/apex/

Cloning into 'apex'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 7872 (delta 10), reused 7 (delta 0), pack-reused 7835
Receiving objects: 100% (7872/7872), 13.99 MiB | 29.30 MiB/s, done.
Resolving deltas: 100% (5357/5357), done.
/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-gasimis7
Created temporary directory: /tmp/pip-req-tracker-r2x2ffho
Created requirements tracker '/tmp/pip-req-tracker-r2x2ffho'
Created temporary directory: /tmp/pip-install-n2z8vt16
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-r2x2ffho'
ERROR: Invalid requirement: '/kaggle/working/apex/'
Hint: It looks like a path. File '/kaggle/working/apex/' does 

In [20]:
!pip install simpletransformers

In [21]:
from simpletransformers.classification import ClassificationModel  #+

In [22]:
#Google colab'da kullanacağımız dosyayı önce aşağıdaki kodu yazarak yüklüyoruz.
from google.colab import files  
uploaded = files.upload()

Saving train.csv to train (1).csv


In [47]:
# Lets import the csv file in pandas dataframe first
train_df = pd.read_csv('train.csv', encoding='utf-8', header=None, names=['duygu', 'text'])

In [48]:
train_df

duygu                                               text
0       1                            3 yıldır tık demedi. :)
1       1                      3 yıldır kullanıyorum müthiş 
2       1  Ürün bugün elime geçti çok fazla inceleme fırs...
3       1  Almaya karar verdim. Hemencecik geldi. Keyifle...
4       1  Günlük kullanımınızı çok çok iyi karsılıyor kı...
5       1                                        gayet güzel
6       1  Çok kaliteli bir ürün ve fiyatı da uygun. Uzun...
7       1  yaklaşık 5 senedir kullanıyorum. defalarca düş...
8       1  Ürün günlük kullanım için çok uygun. Ürünle bi...
9       1  Ürünü bir arkadaşım 2009 yılında hediye olarak...
10      1  1 gün gibi kısa bir sürede elime geçti. Ve bu ...
11      1         fiyat fayda  oranına göre çok iyi bir ürün
12      1  Güzel kullanışlı bir ürün. Herhangi bir proble...
13      1    Oyun oynamayacaklar için gayet güzel bir mouse 
14      1  Ürünü yılladır kullanıyoruz, fiyat kalite ve p...
15      1  Hoş ve kaliteli bir mouse. Leptopla kullanım i...
16      1                                    Urunu begendik 
17      1  Ürünü yorumlara bakarak aldım iyi ki de almışı...
18      1  Ürün süper kalitede değil, malzeme açısından a...
19      1  sağlam ve dayanıklı bir ürün herkese tavsiye e...
20      0  fiyatına göre ortalama bi mause. Oyun için alı...
21      0  hesaplı ve kalıteli ürünler satıkları için ben...
22      0  6 aydır mause kullanıyorum alıcısı ıyı kullanı...
23      0  Fiyat kalite olarak değerlendirdiğinizde güzel...
24      0  Daha önce elimde olan m195 modeline göre çok d...
25      0  Mausum tıklama esnasında tutukluk yapıyor aynı...
26      0  sıradan bir şey almak istiyorsanız, aslı astar...

In [49]:
# Check the df head() diyerek ilk 5 satırı görüyoruz
train_df.head()

duygu                                               text
0      1                            3 yıldır tık demedi. :)
1      1                      3 yıldır kullanıyorum müthiş 
2      1  Ürün bugün elime geçti çok fazla inceleme fırs...
3      1  Almaya karar verdim. Hemencecik geldi. Keyifle...
4      1  Günlük kullanımınızı çok çok iyi karsılıyor kı...

In [55]:
#1 ve 0 dan oluşan bir kategori belirledik
print(train_df.duygu.unique())
print("1 olumlu, 0 olumsuz duygu olarak değerlendirilmiştir.")

[1 0]
1 olumlu, 0 olumsuz duygu olarak değerlendirilmiştir.


In [57]:
# convert string labels to integers
train_df['labels'] = pd.factorize(train_df.duygu)[0]

train_df.head()

duygu                                               text  labels
0      1                            3 yıldır tık demedi. :)       0
1      1                      3 yıldır kullanıyorum müthiş        0
2      1  Ürün bugün elime geçti çok fazla inceleme fırs...       0
3      1  Almaya karar verdim. Hemencecik geldi. Keyifle...       0
4      1  Günlük kullanımınızı çok çok iyi karsılıyor kı...       0

In [58]:
# Let's create a train and test set
from sklearn.model_selection import train_test_split

train, test = train_test_split(train_df, test_size=0.2, random_state=42)

In [59]:
train.shape, test.shape

((21, 3), (6, 3))

In [60]:
# Lets define the model with the parameters (important here is the number of labels and nr of epochs)

model = ClassificationModel('bert', 'bert-base-multilingual-uncased', num_labels=7,args={'reprocess_input_data': True, 'overwrite_output_dir': True, 'num_train_epochs': 2})

Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model 

In [61]:
# Now lets fine tune bert with the train set
model.train_model(train)

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:216: UserWarning: Please also save or load the state of the optimizer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)


(6, 1.749456266562144)

In [62]:
# Let's evaluate this finetuned model with the test set
result, model_outputs, wrong_predictions = model.eval_model(test)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [63]:
predictions = model_outputs.argmax(axis=1)

In [64]:
predictions[0:10]

array([0, 0, 0, 0, 0, 0])

In [65]:
actuals = test.labels.values
actuals[0:10]

array([0, 0, 0, 1, 0, 0])

In [66]:
# Now lets see the accuracy one the test set
from sklearn.metrics import accuracy_score
accuracy_score(actuals, predictions)

0.8333333333333334

In [83]:
sample_text = test.iloc[5]['text']
print(sample_text)

fiyat fayda  oranına göre çok iyi bir ürün


In [69]:
# Lets predict the text of sample_text:
model.predict([sample_text])

(array([0]),
 array([[ 0.79296875,  0.47680664, -0.49145508,  0.07409668, -0.30541992,
         -0.35253906,  0.05633545]]))

In [80]:
# Lets see what the truth was
test.iloc[5]['labels']

0

In [81]:
# And this was category: 
test.iloc[5]['duygu']

1